### ISSUE TITLE
Properly compare signature algorithms in different parts of CMSs

### ISSUE THREAD

**Issue by lolepezy** [lolepezy/rpki-prover#10]
Current implementation using hs-certificate has exactly the same problem of interpreting signature algorithm without parameters and with NULL as equal. 

See
    http://sobornost.net/~job/arin-manifest-issue-2020.08.12.txt,
    https://www.arin.net/announcements/20200812/.

This needs modifying hs-certificate or implementing another custom parser for signature algorithm.

**Comment by job** [comment]
What cryptographic library does `prover` depend on? Perhaps this can be fixed somewhere upstream?

**Comment by job** [comment]
I suspect the lacking algorithmidentifier equivalence checking happens somewhere here https://github.com/vincenthz/hs-certificate/blob/7041244d0dd3946d96af66611b2760d2478e055f/x509/Data/X509/AlgorithmIdentifier.hs but that project seems somewhat unmaintained?

**Comment by lolepezy** [comment]
Yes, that's the one, except that the fork of it is used
https://github.com/lolepezy/hs-certificate
(I had to add some extra functionality to it).

The project is basically kept afloat, without much of development going on.
The lines 111 and 113 are exactly the reasons why NULL parameter in signature is forgotten.

I am planning to fix it in the fork.

**Comment by lolepezy** [comment]
Fixed by
https://github.com/lolepezy/hs-certificate/commit/6102aaee9d971618309eb8365b0029e6f57f86bb
and 
80c3d21d683148626566e717a00076bf75927b0a
