### ISSUE TITLE
Add support for RSC?

### ISSUE THREAD

**Issue by job** [lolepezy/rpki-prover#111]
Hi,

Would you consider adding support for validating and decoding [draft-ietf-sidrops-rpki-rsc](https://datatracker.ietf.org/doc/draft-ietf-sidrops-rpki-rsc/) objects?

The wire format and draft seem stable. WGLC is imminent.

Example objects can be generated using @tomhrr's project at https://github.com/APNIC-net/rpki-rsc-demo or @benmaddison's https://github.com/benmaddison/rpkimancer project

Kind regards,

Job

**Comment by lolepezy** [comment]
Sure, it would take some time, but should be doable.
What should be the output from RSC object?

I mean, VRPs are the output from ROA, some ASPA statements (not yet standardized, I guess) will be the output from ASPA object, what should it be for RSC?

**Comment by lolepezy** [comment]
Hi @job, 
Do you by any chance have an example of a .sig file signed by a certificate in the current RPKI tree?
Or maybe something on a separate TAL?

**Comment by lolepezy** [comment]
Thanks!

**Comment by lolepezy** [comment]
Implemented in 0.4.0 release.
