### ISSUE TITLE
Fix ASPA parser for the latest ASPA version

### ISSUE THREAD

**Issue by lolepezy** [lolepezy/rpki-prover#179]
Probably support both formats and just ignore AFI?

**Comment by timbru** [comment]
I would recommend only supporting the latest ASPA version. There is little deployment today, and for what it's worth Krill 0.14.0 will come out in a week or 2 and automatically migrate existing objects to the new format.

If you have a chance, then perhaps have a look at this v1 object produced by Krill?
rsync://testbed.krill.cloud/repo/testbed-client/0/AS204325.asa

Under the testbed TAL listed on this page (TAL and testbed subject to change):
https://testbed.krill.cloud/ui/testbed

**Comment by lolepezy** [comment]
Ah, that makes things easier indeed.

> If you have a chance, then perhaps have a look at this v1 object produced by Krill?
> rsync://testbed.krill.cloud/repo/testbed-client/0/AS204325.asa

Sure, will do

**Comment by lolepezy** [comment]
Addressed in 
https://github.com/lolepezy/rpki-prover/pull/181

**Comment by lolepezy** [comment]
Done
