### ISSUE TITLE
RRDP desynchronisation detection

### ISSUE THREAD

**Issue by job** [lolepezy/rpki-prover#197]
Would you be interested to implement rrdp desynchronization detection in rpki-prover as described in this draft? https://www.ietf.org/archive/id/draft-spaghetti-sidrops-rrdp-desynchronization-00.html

**Comment by lolepezy** [comment]
Implemented in 
https://github.com/lolepezy/rpki-prover/issues/197

I will prepare a release in the next 2-3 weeks, this change will be in the release.

**Comment by job** [comment]
Great! Thank you for validating this proposal by implementing it

I've added references to your project in the edit buffer https://github.com/job/draft-sidrops-rrdp-desynchronization/commit/2ac52cc5fdfcb5c635d1c6973f965b949c4bd48f

**Comment by lolepezy** [comment]
Cheers!
