### ISSUE TITLE
Sort VRPs

### ISSUE THREAD

**Issue by lolepezy** [lolepezy/rpki-prover#39]
Apparently, it's an important thing
https://github.com/NLnetLabs/routinator/issues/461

**Comment by partim** [comment]
For reference: https://datatracker.ietf.org/doc/html/draft-ietf-sidrops-8210bis-02#section-11

**Comment by lolepezy** [comment]
Thanks!

**Comment by lolepezy** [comment]
Addressed by 
https://github.com/lolepezy/rpki-prover/commit/2a9b1bd290f673b3e06965c2fb83d601a56d65aa
