### ISSUE TITLE
Implement the latest 6486bis whatever it becomes

### ISSUE THREAD

**Issue by lolepezy** [lolepezy/rpki-prover#4]
At the moment it is still a little big of a moving target
https://tools.ietf.org/html/draft-ietf-sidrops-6486bis-03

Strict MFTs, 'failed fetch' concept, etc.

**Comment by job** [comment]
The bis document appears in flux, but robust behavior has been implement in `rpki-client`, `FORT`, and now other validators.

A summary of the procedure is as following:

- fetch the latest manifest (compare time & manifestNumber)
- if the manifest is expired (`nextUpdate` lays in the past): ignore it entirely
- fetch all objects listed on the manifest, check whether the object's SHA256 hash matches the manifest
- if any objects are missing or corrupted (sha256 mismatch), see if the local file cache can supplement 
- if any objects listed on the manifest are missing (even after trying to repair with local cache): ignore it entirely
- if any object is sha256 hash matching, but that referenced object itself is expired or invalid, ignore just that one object
- if a manifest's CRL is missing or expired, ignore the manifest entirely

**Comment by lolepezy** [comment]
Thanks for the summary.

I believe that's pretty much what it does, except for one thing
"if any object is sha256 hash matching, but that referenced object itself is expired or invalid, ignore just that one object"
is implemented as "if any object is sha256 hash matching, but that referenced object itself is expired or invalid, ignore just that one object if it's a certificate otherwise consider the whole manifest invalid".

Such implementation left after following the stricter version of the draft with the exception for the certificates. So the current behavior is stricter that is required by the RFC, but I guess that's the only thing left to adjust to follow the RFC precisely.

**Comment by lolepezy** [comment]
I believe, current behavior is satisfactory.

The latest https://tools.ietf.org/html/draft-ietf-sidrops-6486bis-03 still says
`If there are files listed in
   the manifest that cannot be retrieved from the publication point, or
   if they fail the validity tests specified in [RFC6488], the fetch has
   failed and the RP MUST proceed to`

 I.e. the strictest possible. It looks like that actual implementations have abandoned the idea of being _that_ strict and fell back to the "if any object is sha256 hash matching, but that referenced object itself is expired or invalid, ignore just that one object" behavior. 
 
 This implementation still follows the RFC with the these specific exceptions:
 
  - EE entities referred by the manifest are allowed to be explicitly revoked without making the whole manifest invalid -- these objects are ignored on their own. This one is caused by `cnnic.cn` breaking the whole manifest with revoked ROAs on the manifest.
  - certificates referred by the manifest are allowed to be invalid without making the whole manifest invalid (see previous comment). This is obviously necessary to prevent one delegated CA from invalidating the whole RIR's manifest.

On top of it `invalid fetch` results in falling back to the latest valid cached manifest (i.e. following the https://tools.ietf.org/html/draft-ietf-sidrops-6486bis-03#section-6.7). 

This set of rules seems to be a practically reasonable compromise between following the current RFC 6486-bis as strictly as possible and practical value.
 From the practical point

**Comment by lolepezy** [comment]
In case something else pops up, it's better to open specific issues instead of keeping this one around.

**Comment by job** [comment]
Thank you for sharing your considerations and thoughts on this aspect of the technology stack.
