### ISSUE TITLE
Document requirement for rsync

### ISSUE THREAD

**Issue by agallo** [lolepezy/rpki-prover#46]
For installations that don't have `rsync`, rpki-prover builds and starts fine, but will not function.  This error will be seen in the output
```
[Error]   [21 Apr 2021 15:33:59.193 +00:00] [<unknown loc>] [ThreadId 11] Something weird happened rsync: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory), exiting.
```

Recommendation: document requirement in README.md.  Probably obvious; opening this issue in case others search for this error.

**Comment by lolepezy** [comment]
Thanks for reporting! 
Should be fixed now.
