### ISSUE TITLE
Prefer HTTPS over rsync when fetching the certificate in the TAL

### ISSUE THREAD

**Issue by Koenvh1** [lolepezy/rpki-prover#58]
Most (all?) TALs contain two URIs. Currently, if the first URI is HTTPS, and the second is rsync, it will try the rsync one. 
RFC 8630 recommends preferring the HTTPS URI over the rsync one if both are present:
https://datatracker.ietf.org/doc/html/rfc8630#section-4

**Comment by lolepezy** [comment]
> Currently, if the first URI is HTTPS, and the second is rsync, it will try the rsync one.

Could you give an example of that? Do you mean TA certificate or anything else?

**Comment by lolepezy** [comment]
I think, I know what you mean. The current behaviour is to use the URLs in the order they are enlisted in the TAL (see the previous section in the same RFC).

Anyway, it's now changes to prefer HTTPS. 
Thanks for reporting!.
